<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FinTrack.Api\FinTrack.Api.csproj" />
    <ProjectReference Include="..\..\src\FinTrack.Application\FinTrack.Application.csproj" />
    <ProjectReference Include="..\..\src\FinTrack.Infrastructure\FinTrack.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\FinTrack.Domain\FinTrack.Domain.csproj" />
  </ItemGroup>

</Project>
